version: '3.8'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  backend:
    image: raj96yt/feedback_app_backend:v1.0
    container_name: backend_app
    depends_on:
      - mongodb
    ports:
      - "3000:3000"
    environment:
      MONGODB_URI: "mongodb://mongodb:27017"

  frontend:
    image: raj96yt/feedback_appfronted:v1.0
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "5173:5173"

volumes:
  mongodb_data:
